# Generated by Django 2.1.2 on 2018-12-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='アカウントID')),
                ('pass_hash', models.CharField(max_length=30, verbose_name='パスワードハッシュ')),
                ('email_address', models.EmailField(max_length=30, verbose_name='メールアドレス')),
            ],
        ),
    ]
