# Generated by Django 2.1.2 on 2019-01-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassWordReminder',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='パスワードリマインダーID')),
                ('account_id', models.CharField(max_length=10, verbose_name='アカウントID')),
                ('limit_date', models.DateTimeField(verbose_name='期限')),
                ('onetime_pass_hash', models.CharField(max_length=30, verbose_name='ワンタイムハッシュ')),
                ('delete_flg', models.CharField(max_length=10, verbose_name='削除フラグ')),
                ('register_date', models.DateTimeField(verbose_name='登録日時')),
                ('update_date', models.DateTimeField(verbose_name='更新日時')),
            ],
        ),
    ]
